[package]
name = "lichess-cli"
version = "0.6.0"
edition = "2024"
license = "Apache-2.0"
description = "A cli client for the lichess API."
keywords = ["lichess", "api", "client"]
categories = ["api-bindings"]
homepage = "https://github.com/ion232/lichess-api"
repository = "https://github.com/ion232/lichess-api"

[[bin]]
name = "lichess"
path = "src/main.rs"

[dependencies]
lichess-api = { path = "../lib" }
clap = { version = "4.6.6", features = ["derive"] }
color-eyre = "0.6.5"
futures = "0.3.34"
rand = "0.10.2"
reqwest = "0.13.4"
tokio = { version = "1.53.1", features = ["macros", "rt"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }