[package]
name = "lichess-api"
version = "0.7.0"
edition = "2024"
license = "Apache-2.0"
description = "A client library for the Lichess API"
keywords = ["lichess", "api", "client"]
categories = ["api-bindings", "asynchronous"]
homepage = "https://github.com/ion232/lichess-api"
repository = "https://github.com/ion232/lichess-api"
readme = "../README.md"

[dependencies]
# Library dependencies.
bytes = "1.12.1"
futures = "0.3.34"
futures-core = "0.3.34"
http = "1.5.0"
mime = "0.3.17"
reqwest = { version = "0.13.4", features = ["json", "stream"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_with = { version = "3.22.0", features = ["chrono"] }
serde_urlencoded = "0.7.1"
thiserror = "2.0.20"
tracing = "0.1.44"
url = "2.5.8"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }