// /api/team/{teamId}/arena
// /api/tournament
// /api/tournament/team-battle/{id}
// /api/tournament/{id}
// /api/tournament/{id}/games
// /api/tournament/{id}/join
// /api/tournament/{id}/results
// /api/tournament/{id}/teams
// /api/tournament/{id}/terminate
// /api/tournament/{id}/withdraw
// /api/user/{username}/tournament/created
