// /api/challenge
// /api/challenge/ai
// /api/challenge/open
// /api/challenge/{challengeId}/accept
// /api/challenge/{challengeId}/cancel
// /api/challenge/{challengeId}/decline
// /api/challenge/{gameId}/start-clocks
// /api/challenge/{username}
// /api/round/{gameId}/add-time/{seconds}
// /api/token/admin-challenge