// /api/games/export/_ids
// /api/games/user/{username}
// /api/import
// /api/stream/games-by-users
// /api/stream/games/{streamId}
// /api/stream/games/{streamId}/add
// /api/stream/game/{id}
// /game/export/{gameId}
// /api/user/{username}/current-game
// /api/account/playing