// /team/{teamId}/join
// /team/{teamId}/kick/{userId}
// /team/{teamId}/pm-all
// /team/{teamId}/quit
// /api/team/all
// /api/team/of/{username}
// /api/team/search
// /api/team/{teamId}
// /api/team/{teamId}/request/{userId}/accept
// /api/team/{teamId}/request/{userId}/decline
// /api/team/{teamId}/requests
// /api/team/{teamId}/users